In [20]:
import pandas as pd

In [21]:
df1 = pd.read_csv("LoanStats3a_securev1.csv", skiprows=1)
df2 = pd.read_csv("LoanStats3b_securev1.csv", skiprows=1)
df3 = pd.read_csv("LoanStats3c_securev1.csv", skiprows=1)
df4 = pd.read_csv("LoanStats3d_securev1.csv", skiprows=1)

In [22]:
df4["loan_status"]

0          Fully Paid
1          Fully Paid
2          Fully Paid
3          Fully Paid
4          Fully Paid
5          Fully Paid
6         Charged Off
7          Fully Paid
8          Fully Paid
9          Fully Paid
10         Fully Paid
11         Fully Paid
12         Fully Paid
13         Fully Paid
14         Fully Paid
15        Charged Off
16         Fully Paid
17         Fully Paid
18         Fully Paid
19         Fully Paid
20            Current
21         Fully Paid
22            Current
23         Fully Paid
24         Fully Paid
25         Fully Paid
26        Charged Off
27         Fully Paid
28         Fully Paid
29         Fully Paid
             ...
421067     Fully Paid
421068    Charged Off
421069     Fully Paid
421070        Current
421071        Current
421072     Fully Paid
421073     Fully Paid
421074        Current
421075     Fully Paid
421076    Charged Off
421077     Fully Paid
421078     Fully Paid
421079     Fully Paid
421080     Fully Paid
421081     Fully Paid
421082     Fully Paid
421083     Fully Paid
421084     Fully Paid
421085     Fully Paid
421086     Fully Paid
421087    Charged Off
421088     Fully Paid
421089    Charged Off
421090     Fully Paid
421091     Fully Paid
421092    Charged Off
421093    Charged Off
421094     Fully Paid
421095            NaN
421096            NaN
Name: loan_status, Length: 421097, dtype: object

In [23]:
frames = [df1, df2, df3, df4]
df5 = pd.concat(frames)

In [24]:
df5.to_csv("new.csv")

In [25]:
df5

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,1077501,NaN,5000.0,5000.0,4975.000000,36 months,10.65%,162.87,B,B2,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
1,1077430,NaN,2500.0,2500.0,2500.000000,60 months,15.27%,59.83,C,C4,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
2,1077175,NaN,2400.0,2400.0,2400.000000,36 months,15.96%,84.33,C,C5,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
3,1076863,NaN,10000.0,10000.0,10000.000000,36 months,13.49%,339.31,C,C1,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
4,1075358,NaN,3000.0,3000.0,3000.000000,60 months,12.69%,67.79,B,B5,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
5,1075269,NaN,5000.0,5000.0,5000.000000,36 months,7.90%,156.46,A,A4,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
6,1069639,NaN,7000.0,7000.0,7000.000000,60 months,15.96%,170.08,C,C5,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
7,1072053,NaN,3000.0,3000.0,3000.000000,36 months,18.64%,109.43,E,E1,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
8,1071795,NaN,5600.0,5600.0,5600.000000,60 months,21.28%,152.39,F,F2,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
9,1071570,NaN,5375.0,5375.0,5350.000000,60 months,12.69%,121.45,B,B5,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
10,1070078,NaN,6500.0,6500.0,6500.000000,60 months,14.65%,153.45,C,C3,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
11,1069908,NaN,12000.0,12000.0,12000.000000,36 months,12.69%,402.54,B,B5,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
12,1064687,NaN,9000.0,9000.0,9000.000000,36 months,13.49%,305.38,C,C1,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
13,1069866,NaN,3000.0,3000.0,3000.000000,36 months,9.91%,96.68,B,B1,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
14,1069057,NaN,10000.0,10000.0,10000.000000,36 months,10.65%,325.74,B,B2,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
15,1069759,NaN,1000.0,1000.0,1000.000000,36 months,16.29%,35.31,D,D1,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
16,1065775,NaN,10000.0,10000.0,10000.000000,36 months,15.27%,347.98,C,C4,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
17,1069971,NaN,3600.0,3600.0,3600.000000,36 months,6.03%,109.57,A,A1,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
18,1062474,NaN,6000.0,6000.0,6000.000000,36 months,11.71%,198.46,B,B3,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
19,1069742,NaN,9200.0,9200.0,9200.000000,36 months,6.03%,280.01,A,A1,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
20,1069740,NaN,20250.0,20250.0,19142.161077,60 months,15.27%,484.63,C,C4,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
21,1039153,NaN,21000.0,21000.0,21000.000000,36 months,12.42%,701.73,B,B4,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
22,1069710,NaN,10000.0,10000.0,10000.000000,36 months,11.71%,330.76,B,B3,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
23,1069700,NaN,10000.0,10000.0,10000.000000,36 months,11.71%,330.76,B,B3,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
24,1069559,NaN,6000.0,6000.0,6000.000000,36 months,11.71%,198.46,B,B3,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
25,1069697,NaN,15000.0,15000.0,15000.000000,36 months,9.91%,483.38,B,B1,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
26,1069800,NaN,15000.0,15000.0,8725.000000,36 months,14.27%,514.64,C,C2,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
27,1069657,NaN,5000.0,5000.0,5000.000000,60 months,16.77%,123.65,D,D2,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
28,1069799,NaN,4000.0,4000.0,4000.000000,36 months,11.71%,132.31,B,B3,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
29,1047704,NaN,8500.0,8500.0,8500.000000,36 months,11.71%,281.15,B,B3,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421067,36691397,NaN,20000.0,20000.0,20000.000000,36 months,6.99%,617.46,A,A3,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
421068,36743377,NaN,4200.0,4200.0,4200.000000,36 months,15.99%,147.64,D,D2,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
421069,36331554,NaN,26950.0,26950.0,26950.000000,36 months,8.19%,846.88,A,A5,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
421070,36371802,NaN,15000.0,15000.0,15000.000000,60 months,11.44%,329.44,B,B4,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
421071,36460697,NaN,23000.0,23000.0,23000.000000,60 months,15.59%,554.32,D,D1,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
421072,35773415,NaN,18700.0,18700.0,18700.000000,60 months,17.86%,473.44,D,D5,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
421073,36250801,NaN,6000.0,6000.0,6000.000000,36 months,17.86%,216.50,D,D5,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
421074,36361815,NaN,26500.0,26500.0,26500.000000,60 months,8.67%,545.87,B,B1,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
421075,35591131,NaN,25000.0,25000.0,25000.000000,60 months,15.59%,602.52,D,D1,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
421076,36440728,NaN,25000.0,25000.0,25000.000000,60 months,15.99%,607.82,D,D2,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
421077,36201871,NaN,21000.0,21000.0,21000.000000,36 months,6.03%,639.15,A,A1,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
421078,36381756,NaN,8000.0,8000.0,8000.000000,36 months,8.19%,251.40,A,A5,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
421079,36241316,NaN,6225.0,6225.0,6225.000000,36 months,16.49%,220.37,D,D3,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
421080,36301729,NaN,10000.0,10000.0,10000.000000,36 months,6.49%,306.45,A,A2,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
421081,36250208,NaN,13150.0,13150.0,13150.000000,60 months,14.99%,312.77,C,C5,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
421082,36231724,NaN,12000.0,12000.0,12000.000000,36 months,9.49%,384.34,B,B2,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
421083,36231718,NaN,10775.0,10775.0,10775.000000,36 months,6.03%,327.95,A,A1,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
421084,36381704,NaN,7000.0,7000.0,7000.000000,36 months,14.31%,240.30,C,C4,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
421085,36421485,NaN,4000.0,4000.0,4000.000000,36 months,8.67%,126.59,B,B1,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
421086,35094480,NaN,7500.0,7500.0,7500.000000,36 months,9.49%,240.22,B,B2,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
421087,36260758,NaN,10850.0,10850.0,10850.000000,36 months,19.24%,399.04,E,E2,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
421088,36221446,NaN,11575.0,11575.0,11575.000000,36 months,15.59%,404.61,D,D1,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
421089,36330911,NaN,12000.0,12000.0,12000.000000,36 months,11.99%,398.52,B,B5,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
421090,36441262,NaN,24000.0,24000.0,24000.000000,36 months,11.99%,797.03,B,B5,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
421091,36371250,NaN,10000.0,10000.0,10000.000000,36 months,11.99%,332.10,B,B5,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
421092,36490806,NaN,12000.0,12000.0,12000.000000,60 months,19.99%,317.86,E,E3,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
421093,36271333,NaN,13000.0,13000.0,13000.000000,60 months,15.99%,316.07,D,D2,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
421094,36271262,NaN,20000.0,20000.0,20000.000000,36 months,11.99%,664.20,B,B5,...,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
421095,Total amount funded in policy code 1: 6417608175,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
421096,Total amount funded in policy code 2: 1944088810,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN